---
target_server_type: kvm
hostname: nsgv_04.int.nuage.cf
vmname: nsgv_04


target_server: 172.17.14.40

nsgv_mac: '52:17:14:40:03:01'

bootstrap_method: zfb_iso
nsgv_qcow2_path: /home/soft/5.2.1/unpacked/vns/nsg
nsgv_qcow2_file_name: ncpe_centos7.qcow2



# From Group vars
# Metro vars
mgmt_bridge: nullman
# Remains the same

# Metro vars
data_bridge: nulldata2
# New vars
uplink1_bridge: nulldata2
# uplink2_addess: None


# New vars
#uplink2_bridge: nulldata2
#uplink2_address: 10.88.44.1
#uplink2_prefix: 24

# Metro vars
access_bridge: nullaccess4
images_path: /home/vms
ansible_deployment_host: 172.17.14.40

# New var
images_path_override: True

# New vars, can be defined per NSG ot override
bridge_config:
  nm_controlled: no
  stp: no
  mtu: 9000
