---
- hosts: virgo
  gather_facts: False
  become: False
  remote_user: root

  tasks:
    - name: Getting list of files for directory
      command: 'ls {{ virgo.src_dir }}'
      register: lsdf
    
    - debug:
        var: lsdf
    
    - name: Check this is regular file
      command: "test -f {{ virgo.src_dir }}/{{ item }}"
      with_items: "{{ lsdf.stdout_lines }}"
      failed_when: False
      register: chkrf
    
    - debug:
        var: chkrf

    - name: Debug | Check list of files to copy
      debug: 
        var: item.item
        verbosity: 3
      with_items: "{{ chkrf.results }}"
      when: 'item.rc == 0'

    - name: Copy regular files softare repo directory
      fetch:
        dest: "{{ virgo.dst_dir }}/"
        src: "{{ virgo.src_dir }}/{{ item.item }}"
        flat: yes
      with_items: "{{ chkrf.results }}"
      when: 'item.rc  == 0'