---
- import_tasks: kvm.yml
  when: target_server_type | match("kvm")
  static: no
  tags:
    - nsgv
    - nsgv-predeploy
    - kvm

- import_tasks: aws.yml
  when: target_server_type | match("aws")
  static: no
  tags:
    - nsgv
    - nsgv-predeploy
    - aws

- import_tasks: vcenter.yml
  when: target_server_type | match("vcenter")
  static: no
  tags:
    - nsgv
    - nsgv-predeploy
    - vmware

